apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: thanak81-heyzip-certificate
  namespace: thanak81-heyzip
spec:
  secretName: thanak81-heyzip-secret-tls
  commonName: thanak81-heyzip.assessify.org
  dnsNames:
  - thanak81-heyzip.assessify.org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
