apiVersion: v1
kind: Service
metadata:
  name: thanak81-heyzip-service
spec:
  type: NodePort
  selector:
    app: thanak81-heyzip
  ports:
    - protocol: TCP
      port: 8227
      targetPort: 3000
